# Generated by Django 4.2.4 on 2025-05-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_restaurant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('blocked', 'Blocked')], default='pending', max_length=50),
        ),
    ]
